# Generated by Django 4.2.3 on 2023-08-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.RemoveField(
            model_name="project",
            name="technology",
        ),
        migrations.AddField(
            model_name="project",
            name="technology",
            field=models.ManyToManyField(to="projects.technology"),
        ),
    ]
