# Generated by Django 4.2.3 on 2023-08-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="end_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="start_date",
            field=models.DateField(),
        ),
    ]
